name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Publish
    runs-on: ubuntu

    env:
      SERVER_URL: https://git.snipcola.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: ${{ env.SERVER_URL }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
          run_install: true

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.npm_auth }}
